### ISSUE TITLE
The read function doesn't work

### ISSUE THREAD

**Issue by krysbzh** [gavinhungry/wpi-gpio#3]
Hello guy,
thank you very much for this module. It's very clear and efficient. But there a little issue with the "read" function. When I call it, I receive this error message :
`
node_modules/wpi-gpio/wpi-gpio.js:26
    var cmd = ['gpio', flag, method, pin, args.join(' ')].join(' ');
                                              ^
warn: In script error TypeError: Cannot read property 'join' of undefined
`
The "args" parameter is used in the write function but not in the read one.

Thanks in advance

**Comment by gavinhungry** [comment]
@krysbzh,

Thanks! I must have introduced that when I switched from callbacks to promises. I'll write some tests and tag a new release today.

**Comment by gavinhungry** [comment]
@krysbzh,

See `1.1.0`. You can run the tests with `npm test`. See all changes since `1.0.0` here:
https://github.com/gavinhungry/wpi-gpio/compare/1.0.0...1.1.0

Note that I set the default state of `gpio.BCM_GPIO` back to `false` (as per `README.md`) - if you're using the Broadcom pin numbers and not setting that explicitly to `true`, you will need to do that now.
